-- Problem: New Companies
-- Link: https://www.hackerrank.com/challenges/the-company/problem

SELECT C.COMPANY_CODE, C.FOUNDER, 
(SELECT COUNT(DISTINCT LEAD_MANAGER_CODE) FROM LEAD_MANAGER L WHERE L.COMPANY_CODE=C.COMPANY_CODE) AS TOTAL_LEAD_MANAGERS, 
(SELECT COUNT(DISTINCT SENIOR_MANAGER_CODE) FROM SENIOR_MANAGER S WHERE S.COMPANY_CODE=C.COMPANY_CODE) AS TOTAL_SENIOR_MANAGERS, 
(SELECT COUNT(DISTINCT MANAGER_CODE) FROM MANAGER M WHERE M.COMPANY_CODE=C.COMPANY_CODE) AS TOTAL_MANAGERS, 
(SELECT COUNT(DISTINCT EMPLOYEE_CODE) FROM EMPLOYEE E WHERE E.COMPANY_CODE=C.COMPANY_CODE) AS TOTAL_EMPLOYEES 
FROM COMPANY C ORDER BY C.COMPANY_CODE;