-- Problem: Ollivander's Inventory
-- Link: https://www.hackerrank.com/challenges/harry-potter-and-wands/problem

SELECT 
    W.ID, P.AGE, W.COINS_NEEDED, W.POWER 
FROM WANDS W 
JOIN WANDS_PROPERTY P ON W.CODE=P.CODE
WHERE P.IS_EVIL=0
    AND (W.COINS_NEEDED, W.POWER, P.AGE) IN (
    SELECT 
        MIN(W2.COINS_NEEDED), W2.POWER, P2.AGE
    FROM WANDS W2
    JOIN WANDS_PROPERTY P2 ON W2.CODE=P2.CODE
    WHERE P2.IS_EVIL=0
    GROUP BY W2.POWER,P2.AGE)
ORDER BY W.POWER DESC, P.AGE DESC;