-- Problem: Top Competitors
-- Link: https://www.hackerrank.com/challenges/full-score/problem

SELECT 
    H.HACKER_ID, 
    H.NAME
FROM HACKERS H 
JOIN 
    (SELECT 
        S.HACKER_ID,
        COUNT(*) AS FULL_SCORE_COUNT
    FROM SUBMISSIONS S  
    JOIN CHALLENGES C ON S.CHALLENGE_ID=C.CHALLENGE_ID
    JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL=D.DIFFICULTY_LEVEL
    WHERE S.SCORE=D.SCORE
    GROUP BY S.HACKER_ID
    HAVING COUNT(*)>1
) AS SUB ON H.HACKER_ID=SUB.HACKER_ID
ORDER BY FULL_SCORE_COUNT DESC, H.HACKER_ID;